proxy:
  port: 8998

routing:
  rule: round-robin
  users:
    default:
      behaviour: default
      cluster:
        tags:
          workload: etl
    rules:
      - user: 'team-data-science-(.+)'
        cluster:
          name: 'cluster-00'
          tags:
            workload: interactive

      - user: 'etl-(.+)-(dev|beta|prod)'
        cluster:
          name: 'cluster-01'
          tags:
            workload: etl


clusters:
  sync:
    delay: 10s
  statistics:
    enabled: true
    delay: 5s
  healthcheck:
    enabled: true
    delay: 5s

persistence:
  postgres:
    db: 'postgres'
    host: '127.0.0.1'
    port: 5432
    username: 'trinohub'
    password: 'trino'
    ssl_mode: 'disable'

discovery:
  providers:
    - provider: static
      enabled: true
      static:
        clusters:
          - name: cluster-0
            enabled: true
            url: http://localhost:8080
            tags:
              local: true
              env: dev

    - provider: aws-emr
      enabled: false
      aws:
        access_key_id: ''
        secret_key: ''
        region: 'eu-west-1'
    - provider: k8s
      enabled: false
      k8s:
        kube_config: 'tdac-test'
        cluster_domain: 'cluster.local'
        selector_tags:
          component: 'coordinator'
          deployment: 'trino'

controller:
  autoscaler:
    enabled: true
    kubernetes:
      coordinatorUri: "http://trino-etl.trino-etl.svc.cluster.local:8080"
      namespace: "trino-etl"
      deployment: "trino-etl-worker"
      min: "0"
      max: "5"
      scaleAfter: "10m"
      scaleDownWithRunningQuery: true
  features:
    slow_worker_drainer:
      enabled: true
      gracePeriodSeconds: 300
      dryRun: true
      drainThreshold: 3
      provider: k8s
      k8s:
        namespaceSelector: { }
      analyzer:
        std_deviation_ratio: 1.1

notifier:
  slack:
    webhook: ""

session:
  store:
    redis:
      opts:
        prefix: 'trino::'
        max_ttl: 24h

      standalone:
        enabled: true
        host: '127.0.0.1:6379'
        password: ''
        db: 0

      sentinel:
        enabled: false
        master: 'mymaster'
        hosts: [ '','' ]
        password: ''
        db: 0