services:
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql

  trino:
    image: trinodb/trino
    ports:
      - 8080:8080
    volumes:
      - ./init/trino:/etc/trino